# Generated by Django 4.1.7 on 2023-03-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimage',
            old_name='name',
            new_name='post',
        ),
    ]
