# Generated by Django 4.1.7 on 2023-03-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.petpost'),
        ),
    ]
