# Generated by Django 4.1.7 on 2023-03-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_petimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petimage',
            name='name',
        ),
        migrations.AddField(
            model_name='petpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.petpost'),
        ),
    ]
