# Generated by Django 4.1.7 on 2023-03-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='animal_photos')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('action', models.CharField(blank=True, choices=[('feed', 'Feed'), ('pet', 'Pet')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
