# Generated by Django 4.1.7 on 2023-03-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_animal_remove_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
